### ISSUE TITLE
Unable to run gmlparsing

### ISSUE THREAD

**Issue by MGlauer** [openego/data_processing#28]
I run your program as follows:

`>>>from gmlparsing.RunTool import run`
`gmlparsing.RunTool`
`>>>run()`

Once I select a file I get 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/Dokumente/Development/open_eGo/data_processing/gmlparsing/RunTool.py", line 18, in run
    MakeObjects.execGraphmlFile(myFileName)
  File "/home/martin/Dokumente/Development/open_eGo/data_processing/gmlparsing/MakeObjects.py", line 40, in execGraphmlFile
    tree = ET.parse(myFileName)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1187, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'parallel.graphml'

It seems you are using a relative path in your loading script. Changing this to an absolute path fixes the problem

**Comment by apoorva-ovgu** [comment]
changed,
New way: start the program by using run file
